# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FooChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FooChat
  pod 'Firebase/Core', '~> 4.4.0'
  pod 'Firebase/Auth', '~> 4.4.0'
  pod 'Firebase/Database', '~> 4.4.0'
  pod 'Firebase/Messaging', '~> 4.4.0'
  pod 'Firebase/Storage', '~> 4.4.0'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end

