# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FooChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FooChat
  pod 'Firebase/Core', '~> 4.4.0'
  pod 'Firebase/Auth', '~> 4.4.0'
  pod 'Firebase/Database', '~> 4.4.0'
  pod 'Firebase/Messaging', '~> 4.4.0'
  pod 'Firebase/Storage', '~> 4.4.0'

  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

end

# Temporary workaround for https://github.com/invertase/react-native-firebase/issues/395
post_install do
  `rm -rf Pods/leveldb-library/port/win`
end
